import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Download,LogOut,Search,MessageCircle,CheckCircle2,Clock3,ShieldCheck} from 'lucide-react';
import './styles.css';

const events=['Convera','Dreaden Crypta','Mind Mosaic','Event 4','Event 5','Event 6','Event 7','Event 8','Event 9','Event 10'];
const accounts=events.map(e=>({event:e,email:`${e.toLowerCase().replaceAll(' ','')}@gmail.com`,password:`${e.toLowerCase().replaceAll(' ','')}@123`}));
const master={email:'itekronorganizer@gmail.com',password:'itekron2k26'};
const demo=[
 {name:'Demo Participant',team:'—',email:'participant@example.com',phone:'9876543210',college:'Demo College',department:'IT',year:'3',status:'pending'}
];
function csv(rows:any[]){const head=['Name','Team','Email','Phone','College','Department','Year','WhatsApp Status'];const esc=(v:any)=>`"${String(v??'').replaceAll('"','""')}"`;return [head,...rows.map(r=>[r.name,r.team,r.email,r.phone,r.college,r.department,r.year,r.status])].map(r=>r.map(esc).join(',')).join('\n')}
function App(){const [session,setSession]=useState<any>(null);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [q,setQ]=useState('');const [status,setStatus]=useState<'all'|'pending'|'added'>('all');const [rows,setRows]=useState(demo);const [sort,setSort]=useState<'name'|'college'|'team'|'status'>('name');
 const login=()=>{const found=email===master.email&&password===master.password?{master:true,label:'Master Coordinator'}:accounts.find(a=>a.email===email&&a.password===password);if(found)setSession(found);else alert('Invalid coordinator credentials.');};
 const visible=useMemo(()=>rows.filter(r=>(status==='all'||r.status===status)&&Object.values(r).join(' ').toLowerCase().includes(q.toLowerCase())).sort((a,b)=>String(a[sort]).localeCompare(String(b[sort]))),[rows,q,status,sort]);
 if(!session)return <main className="login"><div className="glow"/><section className="login-card"><div className="brand">ITEKRON <span>2K26</span></div><div className="eyebrow"><ShieldCheck size={14}/> COORDINATOR PORTAL</div><h1>Event operations,<br/><em>made simple.</em></h1><p>Sign in to view your assigned participants and manage WhatsApp group status.</p><input placeholder="Coordinator email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={login}>Sign in</button><small>Each coordinator account is restricted to its assigned event.</small></section></main>;
 return <main className="app"><header><div><div className="brand">ITEKRON <span>2K26</span></div><div className="sub">Coordinator Portal</div></div><div className="head-right"><b>{session.master?'All Events':session.event}</b><button className="icon-btn" onClick={()=>setSession(null)}><LogOut size={18}/></button></div></header><section className="hero"><div><div className="eyebrow"><ShieldCheck size={14}/> {session.master?'MASTER ACCESS':'EVENT ACCESS'}</div><h1>{session.master?'Coordinator overview':`${session.event} participants`}</h1><p>Live data from the registration database. Update only the WhatsApp status.</p></div><button className="export" onClick={()=>{const blob=new Blob([csv(visible)],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${session.master?'itekron-all':session.event.toLowerCase().replaceAll(' ','-')}-participants.csv`;a.click();URL.revokeObjectURL(a.href)}}><Download size={16}/> Export CSV</button></section><section className="stats"><div><strong>{visible.length}</strong><span>Showing</span></div><div><strong>{rows.filter(r=>r.status==='added').length}</strong><span>WhatsApp added</span></div><div><strong>{rows.filter(r=>r.status==='pending').length}</strong><span>Pending</span></div></section><section className="toolbar"><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, team, phone, college..."/></div><div className="filters">{(['all','pending','added'] as const).map(s=><button className={status===s?'active':''} onClick={()=>setStatus(s)} key={s}>{s==='all'?'All':s==='pending'?'Pending':'Added'}</button>)}</div></section><div className="table-wrap"><table><thead><tr>{[['name','Name'],['team','Team'],['college','College'],['status','WhatsApp']].map(([k,l])=><th onClick={()=>setSort(k as any)} key={k}>{l}</th>)}<th>Contact</th></tr></thead><tbody>{visible.map((r,i)=><tr key={i}><td><b>{r.name}</b><small>{r.email}</small></td><td>{r.team}</td><td>{r.college}<small>{r.department} · Year {r.year}</small></td><td><button className={`status ${r.status}`} onClick={()=>setRows(x=>x.map((z,j)=>j===i?{...z,status:z.status==='added'?'pending':'added'}:z))}>{r.status==='added'?<CheckCircle2 size={15}/>:<Clock3 size={15}/>} {r.status==='added'?'Added':'Pending'}</button></td><td><a className="wa" href={`https://wa.me/91${r.phone}`} target="_blank"><MessageCircle size={15}/> WhatsApp</a></td></tr>)}</tbody></table></div></main>}
createRoot(document.getElementById('root')!).render(<App/>);